version: '3'
services:
 node-app:
  build: .
  ports:
   - "3333:3000"
   - "4000:4000"
  env_file:
   - ./.env
  depends_on:
   - escrawme-db
 escrawme-db:
   image: mongo
   environment:
    - MONGO_INITDB_ROOT_USERNAME=abderrahman
    - MONGO_INITDB_ROOT_PASSWORD=localhost
   volumes:
    - mongo-db:/data/db

volumes:
 mongo-db:
 

  